In [165]:
import numpy as np 
import pandas as pd 
import random
import matplotlib.pyplot as plt

In [166]:
dataframe = pd.read_csv('./obesity_data.csv')
print(dataframe)

     Age  Gender      Height     Weight        BMI  PhysicalActivityLevel  \
0     56    Male  173.575262  71.982051  23.891783                      4   
1     69    Male  164.127306  89.959256  33.395209                      2   
2     46  Female  168.072202  72.930629  25.817737                      4   
3     32    Male  168.459633  84.886912  29.912247                      3   
4     60    Male  183.568568  69.038945  20.487903                      3   
..   ...     ...         ...        ...        ...                    ...   
995   18    Male  155.588674  64.103182  26.480345                      4   
996   35  Female  165.076490  97.639771  35.830783                      1   
997   49  Female  156.570956  78.804284  32.146036                      1   
998   64    Male  164.192222  57.978115  21.505965                      4   
999   66  Female  178.537130  74.962164  23.517168                      1   

    ObesityCategory  
0     Normal weight  
1             Obese  
2        

In [167]:
data = np.array(dataframe)
print(data)
# getting data and processing data
for i in range(data.shape[0]):
    for j in range(data.shape[1]):
        # Male is 1 and Female is 0
        if data[i,j] == 'Male':
            data[i,j] = 1
        if data[i,j] == 'Female':
            data[i,j] = 0
        # Normal Weight = 0, Overweight = 1, Obese = 2
        if data[i,j] == 'Underweight':
            data[i,j] = 1
        if data[i,j] == 'Normal weight':
            data[i,j] = 2
        if data[i,j] == 'Overweight':
            data[i,j] = 3
        if data[i,j] == 'Obese':
            data[i,j] = 4
        
        # data whitening // can be done later
        
print('Processed Data')
print(data)

[[56 'Male' 173.5752624383722 ... 23.89178262396797 4 'Normal weight']
 [69 'Male' 164.1273058223382 ... 33.39520945079775 2 'Obese']
 [46 'Female' 168.0722021276139 ... 25.81773745564312 4 'Overweight']
 ...
 [49 'Female' 156.57095601730393 ... 32.14603570597436 1 'Obese']
 [64 'Male' 164.1922221149603 ... 21.505964950969545 4 'Normal weight']
 [66 'Female' 178.5371304568283 ... 23.51716758335692 1 'Normal weight']]
Processed Data
[[56 1 173.5752624383722 ... 23.89178262396797 4 2]
 [69 1 164.1273058223382 ... 33.39520945079775 2 4]
 [46 0 168.0722021276139 ... 25.81773745564312 4 3]
 ...
 [49 0 156.57095601730393 ... 32.14603570597436 1 4]
 [64 1 164.1922221149603 ... 21.505964950969545 4 2]
 [66 0 178.5371304568283 ... 23.51716758335692 1 2]]


In [168]:

x = data[:,:6]
y = data[:,6:]
print(data.shape)

# # to be commented
# np.random.seed(0)
# random.seed(0)

# dividing test data and training data
n = data.shape[0]
training_indices = random.sample(range(n),int(0.8*n))
test_indices = list(set(range(n)) - set(training_indices))
training_indices.sort()
test_indices.sort()
print(training_indices)
print(test_indices)
x_test = np.array([x[i] for i in test_indices])
x_training = np.array([x[i] for i in training_indices])
y_test = np.array([y[i] for i in test_indices])
y_training = np.array([y[i] for i in training_indices])
print(x_test.shape)
print(x_training.shape)
print(y_test.shape)
print(y_training.shape)

(1000, 7)
[0, 1, 2, 3, 4, 5, 6, 7, 11, 12, 13, 14, 16, 18, 19, 20, 21, 22, 23, 24, 26, 27, 28, 29, 31, 33, 34, 35, 37, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 56, 58, 59, 60, 61, 62, 63, 64, 66, 67, 68, 69, 70, 71, 72, 75, 76, 77, 80, 81, 82, 83, 84, 85, 86, 87, 90, 91, 94, 95, 96, 98, 99, 100, 101, 102, 103, 104, 105, 107, 108, 109, 110, 112, 113, 115, 117, 119, 120, 121, 122, 123, 125, 126, 127, 128, 129, 130, 131, 132, 134, 135, 137, 138, 141, 142, 143, 144, 146, 147, 149, 150, 153, 154, 155, 157, 159, 160, 164, 165, 166, 167, 168, 169, 170, 171, 173, 175, 176, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 190, 191, 192, 193, 194, 195, 196, 197, 198, 200, 201, 202, 203, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 217, 218, 220, 221, 222, 224, 225, 226, 228, 229, 230, 231, 232, 235, 236, 237, 238, 239, 240, 241, 245, 246, 247, 248, 249, 250, 251, 253, 254, 255, 256, 257, 259, 261, 262, 263, 264, 266, 268, 269, 270, 271, 272, 273, 274, 275, 

In [169]:
def distance(Xarray1,Xarray2):
    '''Lenth of Xarray1 and Xarray 2 should be same'''
    dis = 0
    for i in range(len(Xarray1)):
        dis += (Xarray1[i] - Xarray2[i])**2
    return dis**0.5

def Accuracy(x_test,y_test,y_predicted):
    n = len(x_test)
    m = 0
    for i in range(n):
        if y_test[i] == y_predicted[i]:
            m += 1
    return round(m/n,3)

def mode(l):
    d = {}
    for i in l:
        if i in d:
            d[i] += 1
        else:
            d[i] = 1
    return max(d,key= d.get)

def KNNClassifier(x_test , x_training, y_training, k):
    y_predicted = []
    for test_point in x_test:
        l = []
        for i in range(len(x_training)):
            l.append([ y_training[i,0] , distance(test_point, x_training[i][:]) ])
        l.sort(key= lambda x : x[1])
        y_predicted.append(mode(l[:k][0]))
    return y_predicted

y_predicted = KNNClassifier(x_test , x_training, y_training, 25)
print(Accuracy(x_test,y_test,y_predicted))

0.93


In [171]:
# Age,Gender,Height,Weight,BMI,PhysicalActivityLevel
x_test2 = np.array([[45,0,178,100,25.8,4]])
print(KNNClassifier(x_test2 , x_training, y_training, 25))

[4]


In [175]:
age = int(input("Enter your Age: "))
gender = input("Enter your Gender: ")
if gender.lower() == 'male':
    gender = 1
else:
    gender = 0
height = int(input("Enter your Height(cm): "))
weight = int(input("Enter your Weight(kg)"))
BMI = weight/(height/100)**2 # weight in kg / (height in meter)**2
PyAct = int(input("Rate your physical Activy in rate of 1 to 4: "))
l = [age,gender,height,weight,BMI,PyAct]
print(l)
x_test3 = np.array([l])
Pclass = KNNClassifier(x_test3 , x_training, y_training, 25)
if Pclass == [1]:
    print('You are Underweight! You should eat more !')
if Pclass == [2]:
    print('You are Normal weight')
if Pclass == [3]:
    print('You are Overweight')
if Pclass == [4]:
    print('You are Obese! You should workout !')


[41, 0, 160, 63, 24.609374999999996, 2]
You are Normal weight
